{% set name = "accelerate" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/accelerate-{{ version }}.tar.gz
  sha256: e8f43a55bcbe0ff6fb3d7f03335b026fda11c7b35f3666f86c148ea528bdb2a0

build:
  number: 0
  noarch: python
  entry_points:
    - accelerate=accelerate.commands.accelerate_cli:main
    - accelerate-config=accelerate.commands.config:main
    - accelerate-launch=accelerate.commands.launch:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - packaging
    - numpy >=1.17
    - python >=3.6
    - pyyaml
    - pytorch >=1.4.0

test:
  imports:
    - accelerate
    - accelerate.commands
  commands:
    - pip check
    - accelerate --help
    - accelerate-config --help
    - accelerate-launch --help
  requires:
    - pip

about:
  home: https://github.com/huggingface/accelerate
  doc_url: https://huggingface.co/docs/accelerate
  summary: Training loop of PyTorch without boilerplate code
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
