{% set name = "accelerate" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/accelerate-{{ version }}.tar.gz
  sha256: 438e25a01afa6e3ffbd25353e76a68be49677c3050f10bfac7beafaf53503efc

build:
  number: 0
  skip: true  # [py<37]
  entry_points:
    - accelerate=accelerate.commands.accelerate_cli:main
    - accelerate-config=accelerate.commands.config:main
    - accelerate-launch=accelerate.commands.launch:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - numpy >=1.17
    - packaging >=20.0
    - psutil
    - pytorch >=1.4.0,<3
    - pyyaml

test:
  imports:
    - accelerate
    - accelerate.commands
  commands:
    - pip check
    - accelerate --help
    - accelerate-config --help
    - accelerate-launch --help
  requires:
    - datasets
    - pip
    - sentencepiece
    - transformers
    - tokenizers !=0.11.3,<0.13,>=0.11.1

about:
  home: https://github.com/huggingface/accelerate
  summary: Training loop of PyTorch without boilerplate code
  description: |
    Accelerate was created for PyTorch users who like to write the training loop of PyTorch models but are reluctant to write and maintain the boilerplate code needed to use multi-GPUs/TPU/fp16.

    Accelerate abstracts exactly and only the boilerplate code related to multi-GPUs/TPU/fp16 and leaves the rest of your code unchanged.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  license_url: https://github.com/huggingface/accelerate/blob/v{{ version }}/LICENSE
  doc_url: https://huggingface.co/docs/accelerate/index
  doc_source_url: https://github.com/huggingface/accelerate/tree/main/docs/source
  dev_url: https://github.com/huggingface/accelerate

extra:
  recipe-maintainers:
    - thewchan
