{% set name = "accelerate" %}
{% set version = "1.4.0" %}

package:
  name: huggingface_{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 37d413e1b64cb8681ccd2908ae211cf73e13e6e636a2f598a96eccaa538773a5

build:
  number: 0
  skip: true  # [py<39]
  entry_points:
    - accelerate=accelerate.commands.accelerate_cli:main
    - accelerate-config=accelerate.commands.config:main
    - accelerate-estimate-memory=accelerate.commands.estimate:main
    - accelerate-launch=accelerate.commands.launch:main
    - accelerate-merge-weights=accelerate.commands.merge:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - numpy >=1.17,<3.0.0
    - packaging >=20.0
    - psutil
    - pytorch >=2.0.0  # [linux]
    # pytorch first built with USE_DISTRIBUTED=1 at v2.0.1 for win/osx.
    - pytorch >=2.0.1  # [win or osx]
    - huggingface_hub >=0.21.0
    - pyyaml
    - safetensors >=0.4.3

test:
  requires:
    - pip
  imports:
    - accelerate
  commands:
    - pip check
    - set "PYTHONIOENCODING=utf8"  # [win]
    - accelerate --help
    - accelerate-config --help
    - accelerate-launch --help
    - accelerate-estimate-memory --help
    - accelerate-merge-weights --help

about:
  home: https://github.com/huggingface/accelerate
  summary: Training loop of PyTorch without boilerplate code
  description: |
    Accelerate was created for PyTorch users who like to write the training loop of PyTorch models but are reluctant to write and maintain the boilerplate code needed to use multi-GPUs/TPU/fp16.

    Accelerate abstracts exactly and only the boilerplate code related to multi-GPUs/TPU/fp16 and leaves the rest of your code unchanged.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://huggingface.co/docs/accelerate/index
  dev_url: https://github.com/huggingface/accelerate

extra:
  recipe-maintainers:
    - thewchan
