{% set name = "accelerate" %}
{% set version = "0.20.3" %}

package:
  name: huggingface_{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/accelerate-{{ version }}.tar.gz
  sha256: 79a896978c20dac270083d42bf033f4c9a80dcdd6b946f1ca92d8d6d0f0f5ba9

build:
  number: 0
  # Windows is currently missing USE_DISTRIBUTED flag in pytorch.
  skip: true  # [py<37 or win]
  # ppc64le is missing pytorch for 3.11
  skip: true  # [py>310 and (linux and ppc64le)]
  entry_points:
    - accelerate=accelerate.commands.accelerate_cli:main
    - accelerate-config=accelerate.commands.config:main
    - accelerate-launch=accelerate.commands.launch:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    # https://github.com/huggingface/accelerate/blob/665d5180fcc01d5700f7a9aa3f9bdb75c6055dce/src/accelerate/utils/torch_xla.py#L18
    - setuptools
    - numpy >=1.17
    - packaging >=20.0
    - psutil
    - pytorch >=1.6.0
    - pyyaml
    # https://github.com/huggingface/accelerate/blob/v0.20.3/src/accelerate/utils/versions.py#L23
    - importlib_metadata # [py<38]

test:
  requires:
    - pip
  imports:
    - accelerate
    - accelerate.commands
  commands:
    - pip check
    - accelerate --help
    - accelerate-config --help
    - accelerate-launch --help

about:
  home: https://github.com/huggingface/accelerate
  summary: Training loop of PyTorch without boilerplate code
  description: |
    Accelerate was created for PyTorch users who like to write the training loop of PyTorch models but are reluctant to write and maintain the boilerplate code needed to use multi-GPUs/TPU/fp16.

    Accelerate abstracts exactly and only the boilerplate code related to multi-GPUs/TPU/fp16 and leaves the rest of your code unchanged.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://huggingface.co/docs/accelerate/index
  dev_url: https://github.com/huggingface/accelerate

extra:
  recipe-maintainers:
    - thewchan
